// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// arrApply
SEXP arrApply(NumericVector arr, int idim, std::string fun);
RcppExport SEXP arrApply_arrApply(SEXP arrSEXP, SEXP idimSEXP, SEXP funSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type arr(arrSEXP);
    Rcpp::traits::input_parameter< int >::type idim(idimSEXP);
    Rcpp::traits::input_parameter< std::string >::type fun(funSEXP);
    __result = Rcpp::wrap(arrApply(arr, idim, fun));
    return __result;
END_RCPP
}
